DROP TABLE BOOK;

CREATE TABLE BOOK (
  BOOK_NO NUMBER PRIMARY KEY,
  BOOK_TITLE VARCHAR2(500) NOT NULL,
  BOOK_WRITER VARCHAR2(100) NOT NULL,
  BOOK_EDITOR VARCHAR2(100),
  BOOK_PUBLISHER VARCHAR2(100) NOT NULL,
  STOCK NUMBER NOT NULL,
  STORY VARCHAR2(1000),  -- 줄거리 길이 증가
  BOOK_LIKE NUMBER DEFAULT 0,
  VOTE_RESULT NUMBER DEFAULT 0,
  G_CODE VARCHAR2(100),
  
  CONSTRAINT BOOK_G_CODE FOREIGN KEY (G_CODE) 
  REFERENCES GENRE(G_CODE) ON DELETE CASCADE
);

COMMENT ON COLUMN BOOK.BOOK_NO IS '책번호';
COMMENT ON COLUMN BOOK.BOOK_TITLE IS '책제목';
COMMENT ON COLUMN BOOK.BOOK_WRITER IS '지은이';
COMMENT ON COLUMN BOOK.BOOK_EDITOR IS '엮은이';
COMMENT ON COLUMN BOOK.BOOK_PUBLISHER IS '출판사';
COMMENT ON COLUMN BOOK.STOCK IS '보유수';
COMMENT ON COLUMN BOOK.STORY IS '줄거리';
COMMENT ON COLUMN BOOK.BOOK_LIKE IS '좋아요수';
COMMENT ON COLUMN BOOK.VOTE_RESULT IS '투표결과';