DROP TABLE BOOK;
DROP TABLE GENRE;

CREATE TABLE GENRE(
    G_CODE VARCHAR2(100) NOT NULL,
    G_NAME VARCHAR2(60) NOT NULL
); 

COMMENT ON COLUMN GENRE.G_CODE IS '장르 CODE';
COMMENT ON COLUMN GENRE.G_NAME IS '장르명';

CREATE TABLE BOOK(
  BOOK_NO NUMBER PRIMARY KEY,
  BOOK_TITLE VARCHAR2(500) NOT NULL,
  BOOK_WRITER VARCHAR2(100) NOT NULL,
  BOOK_EDITOR VARCHAR2(100) NOT NULL,
  BOOK_PUBLISHER VARCHAR2(100),
  STOCK NUMBER NOT NULL,
  STORY VARCHAR2(100),
  BOOK_LIKE NUMBER ,
  VOTE_RESULT NUMBER,
  
);
