DROP TABLE ATTACHMENT;

CREATE TABLE ATTACHMENT(
    FILE_NO NUMBER CONSTRAINT FILE_NO_PK PRIMARY KEY,
    WRITE_NO NUMBER CONSTRAINT WRITE_NO_FK REFERENCES BOARD ON DELETE CASCADE NOT NULL,
    ORIGIN_NAME VARCHAR2(255 BYTE) CONSTRAINT ORIGIN_NAME_NN NOT NULL,
    CHANGE_NAME VARCHAR2(255 BYTE) CONSTRAINT CHANGE_NAME_NN NOT NULL,
    FILE_PATH VARCHAR2(1000 BYTE),
    UPLOAD_DATE DATE DEFAULT SYSDATE CONSTRAINT UPLOAD_DATE_NN NOT NULL,
    STATUS VARCHAR2(1 BYTE) DEFAULT 'Y'
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.WRITE_NO IS '글번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드 날짜';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '활성화 여부';




