DROP TABLE BOARD_ANSWER;

CREATE TABLE BOARD_ANSWER(
    B_ANSWER_NO NUMBER CONSTRAINT B_ANSWER_NO_PK PRIMARY KEY,
    B_ANSWER VARCHAR2(4000) CONSTRAINT B_ANSWER_NN NOT NULL
);

COMMENT ON COLUMN BOARD_ANSWER.B_ANSWER_NO IS '게시글 답글 번호';
COMMENT ON COLUMN BOARD_ANSWER.B_ANSWER IS '게시글 답글 내용';