DROP TABLE LIBRARY;

CREATE TABLE LIBRARY(
    L_NO NUMBER CONSTRAINT L_NO_PK PRIMARY KEY,
    L_NAME VARCHAR2(50) CONSTRAINT L_NAME_NN NOT NULL,
    L_LATITUDE NUMBER CONSTRAINT L_LATITUDE_NN NOT NULL,
    L_LONGITUDE NUMBER CONSTRAINT L_LONGITUDE_NN NOT NULL,
    L_LOCATION_NAME VARCHAR2(50) CONSTRAINT L_LOCATION_NAME_NN NOT NULL,
    L_LOCATION VARCHAR2(50) CONSTRAINT L_LOCATION_NN NOT NULL,
    HOLIDAYINFO DATE,
    L_OPEN VARCHAR(10),
    L_END VARCHAR2(10),
    DOCU_COUNT NUMBER CONSTRAINT DOCU_COUNT_NN NOT NULL,
    L_TEL VARCHAR2(20),
    L_ADDRESS VARCHAR2(50) CONSTRAINT L_ADDRESS_NN NOT NULL
);

COMMENT ON COLUMN LIBRARY.L_NO IS '서고번호';
COMMENT ON COLUMN LIBRARY.L_NAME IS '서고이름';
COMMENT ON COLUMN LIBRARY.L_LATITUDE IS '서고위도';
COMMENT ON COLUMN LIBRARY.L_LONGITUDE IS '서고경도';
COMMENT ON COLUMN LIBRARY.L_LOCATION_NAME IS '서고 시도명';
COMMENT ON COLUMN LIBRARY.L_LOCATION IS '서고 시군구';
COMMENT ON COLUMN LIBRARY.HOLIDAYINFO IS '휴관일 정보';
COMMENT ON COLUMN LIBRARY.L_OPEN IS '운영시작일시';
COMMENT ON COLUMN LIBRARY.L_END IS '운영종료일시';
COMMENT ON COLUMN LIBRARY.DOCU_COUNT IS '자료수';
COMMENT ON COLUMN LIBRARY.L_TEL IS '서고 전화번호';
COMMENT ON COLUMN LIBRARY.L_ADDRESS IS '서고 도로명주소';