DROP TABLE FOLLOW;

CREATE TABLE FOLLOW(
    FOLLOWER_ID NUMBER,
    FOLLOWING_ID NUMBER CONSTRAINT FOLLOWING_ID_FK REFERENCES MEMBER ON DELETE CASCADE NOT NULL,
    
    CONSTRAINT FOLLOW_PFK PRIMARY KEY(FOLLOWER_ID,FOLLOWING_ID) 
);

COMMENT ON COLUMN FOLLOW.FOLLOWER_ID IS '팔로우를 시도한 사람 ID';
COMMENT ON COLUMN FOLLOW.FOLLOWING_ID IS '팔로우 할 대상 ID';
