DROP TABLE BOARD;

CREATE TABLE BOARD(
    WRITE_NO NUMBER CONSTRAINT WRITE_NO_PK PRIMARY KEY,
    WRITE_TITLE VARCHAR2(150) CONSTRAINT WRITE_TITLE_NN NOT NULL,
    WRITE_CONTENT VARCHAR2(4000) CONSTRAINT WRITE_CONTENT_NN NOT NULL,
    WRITER NUMBER CONSTRAINT WRITER_FK REFERENCES MEMBER ON DELETE CASCADE NOT NULL,
    B_ANSWER_NO NUMBER CONSTRAINT B_ANSWER_NO_FK REFERENCES BOARD_ANSWER ON DELETE CASCADE NOT NULL,
    COUNT NUMBER DEFAULT 0,
    WRITE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD.WRITE_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.WRITE_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.WRITE_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.WRITER IS '게시글 작성자';
COMMENT ON COLUMN BOARD.B_ANSWER_NO IS '게시글에 대한 답글 번호';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.WRITE_DATE IS '작성일자';
