DROP TABLE VOTE;

CREATE TABLE VOTE(
    VOTE_NO NUMBER CONSTRAINT VOTE_NO_PK PRIMARY KEY,
    MEM_NO NUMBER CONSTRAINT VOKE_MEM_NO_FK REFERENCES MEMBER ON DELETE CASCADE NOT NULL 
);

COMMENT ON COLUMN VOTE.VOTE_NO IS '투표번호ID';
COMMENT ON COLUMN VOTE.MEM_NO IS '사용자 번호';